#!/bin/bash

if [ $COLLECT_RLOGS ]; then
  # Generate SSH Keys
  if [ -f "/home/nnlc/.ssh/comma" ] && [ -f "/home/nnlc/.ssh/comma.pub" ]; then
    echo "Existing SSH keys found"
  elif [ -f "/input/comma.pub" ] && [ -f "/input/comma" ]; then
    # use existing keys if available
    echo "SSH keys found in /inputs."
    cp /input/comma /home/nnlc/.ssh/comma
    cp /input/comma.pub /home/nnlc/.ssh/comma.pub
  else
    # Generate keys if none already exist and none found under /input
    echo "No usable SSH keys found. Generating new keys"
    ssh-keygen -t ed25519 -f /home/nnlc/.ssh/comma -N ""

    # keys need to be stored to a persistent volume so they aren't regenerated whenever the container is recreated
    echo "Persisting keys under /input"
    cp /home/nnlc/.ssh/comma /input/comma
    cp /home/nnlc/.ssh/comma.pub /input/comma.pub
  fi

  # Add SSH config file entry for comma
  echo "Adding SSH config for comma device"
  touch /home/nnlc/.ssh/config
  echo "Host comma" > /home/nnlc/.ssh/config
  echo "User comma" > /home/nnlc/.ssh/config
  echo "Hostname $COMMA_IP" > /home/nnlc/.ssh/config

  if [ $AUTOMATE_RLOGS ]; then
    # Set up rlog collection cronjob
    if [[ -f "/etc/crontabs/nnlc" ]]; then
      touch /etc/crontabs/nnlc
      chown "nnlc":"nnlc" "/etc/crontabs/nnlc"
      crontab -u "nnlc" "/etc/crontabs/nnlc"
    fi
    (crontab -u nnlc -l ; echo "00 0-23/6 * * * /home/nnlc/rlog_collect.sh") | crontab -
  fi

fi