---
services:
  nnlc:
    image: ghcr.io/chendrick00/sp-nnlc-docker:master
    pull_policy: missing
    container_name: nnlc
    environment:
      - COMMA_IP=xxx.xxx.xxx.xxx
      - DEVICE_ID=DEVICE_ID_HERE
      - ENABLE_RLOGS_IMPORTER=true
      - ENABLE_RLOGS_SCHEDULER=true
      - RLOGS_SCHEDULE='0 0-23/6 * * *'
      - VEHICLE=vehicle
      - TZ=America/Los_Angeles
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /opt/nnlc:/data